from __future__ import annotations

import json
import os
import tempfile
from base64 import urlsafe_b64encode
from contextlib import contextmanager
from pathlib import Path
from typing import Any, Iterator

from cryptography.fernet import Fernet, InvalidToken

from core.storage_service import system_state_path, user_state_path

_KEY_ENV = "IKAROS_COOKIE_ENCRYPTION_KEY"


def _safe_platform(platform: str) -> str:
    value = str(platform or "").strip().lower()
    if not value or not value.replace("_", "").replace("-", "").isalnum():
        raise ValueError("invalid platform name")
    return value


def _key_path() -> Path:
    return system_state_path("download_video", "browser_sessions.key")


def _session_path(user_id: int | str, platform: str) -> Path:
    return user_state_path(
        user_id,
        "download_video",
        f"{_safe_platform(platform)}.cookies.enc",
    )


def _write_private(path: Path, payload: bytes) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    temp_path = path.with_suffix(path.suffix + ".tmp")
    temp_path.write_bytes(payload)
    os.chmod(temp_path, 0o600)
    temp_path.replace(path)
    os.chmod(path, 0o600)


def _load_or_create_key() -> bytes:
    configured = str(os.getenv(_KEY_ENV) or "").strip().encode("ascii", errors="ignore")
    if configured:
        try:
            Fernet(configured)
            return configured
        except Exception as exc:
            raise RuntimeError(f"{_KEY_ENV} 不是有效的 Fernet 密钥") from exc

    path = _key_path()
    if path.exists():
        key = path.read_bytes().strip()
        Fernet(key)
        return key

    key = urlsafe_b64encode(os.urandom(32))
    _write_private(path, key)
    return key


def _fernet() -> Fernet:
    return Fernet(_load_or_create_key())


def save_browser_cookies(
    user_id: int | str,
    platform: str,
    cookies: list[dict[str, Any]],
) -> int:
    normalized = []
    for item in cookies:
        if not isinstance(item, dict):
            continue
        name = str(item.get("name") or "").strip()
        domain = str(item.get("domain") or "").strip().lower()
        if not name or not domain:
            continue
        normalized.append(
            {
                "name": name,
                "value": str(item.get("value") or ""),
                "domain": domain,
                "path": str(item.get("path") or "/"),
                "expires": int(float(item.get("expires") or 0)),
                "httpOnly": bool(item.get("httpOnly")),
                "secure": bool(item.get("secure")),
                "sameSite": str(item.get("sameSite") or ""),
            }
        )

    payload = json.dumps(
        {
            "version": 1,
            "platform": _safe_platform(platform),
            "cookies": normalized,
        },
        ensure_ascii=False,
        separators=(",", ":"),
    ).encode("utf-8")
    _write_private(_session_path(user_id, platform), _fernet().encrypt(payload))
    return len(normalized)


def load_browser_cookies(
    user_id: int | str,
    platform: str,
) -> list[dict[str, Any]]:
    path = _session_path(user_id, platform)
    if not path.exists():
        return []
    try:
        payload = json.loads(_fernet().decrypt(path.read_bytes()).decode("utf-8"))
    except (InvalidToken, ValueError, json.JSONDecodeError, OSError):
        return []
    cookies = payload.get("cookies") if isinstance(payload, dict) else None
    return [dict(item) for item in (cookies or []) if isinstance(item, dict)]


def has_browser_session(user_id: int | str, platform: str) -> bool:
    return bool(load_browser_cookies(user_id, platform))


def _render_netscape(cookies: list[dict[str, Any]]) -> str:
    lines = ["# Netscape HTTP Cookie File", "# Generated by Ikaros; do not edit."]
    for item in cookies:
        domain = str(item.get("domain") or "").strip()
        name = str(item.get("name") or "").strip()
        if not domain or not name:
            continue
        include_subdomains = "TRUE" if domain.startswith(".") else "FALSE"
        secure = "TRUE" if item.get("secure") else "FALSE"
        expires = max(0, int(float(item.get("expires") or 0)))
        path = str(item.get("path") or "/")
        value = str(item.get("value") or "")
        lines.append(
            "\t".join(
                (domain, include_subdomains, path, secure, str(expires), name, value)
            )
        )
    return "\n".join(lines) + "\n"


@contextmanager
def materialized_cookie_file(
    user_id: int | str,
    platform: str | None,
) -> Iterator[str | None]:
    cookies = load_browser_cookies(user_id, platform) if platform else []
    if not cookies:
        yield None
        return

    descriptor, raw_path = tempfile.mkstemp(
        prefix="ikaros-yt-dlp-cookies-",
        suffix=".txt",
    )
    path = Path(raw_path)
    try:
        with os.fdopen(descriptor, "w", encoding="utf-8") as handle:
            handle.write(_render_netscape(cookies))
        os.chmod(path, 0o600)
        yield str(path)
    finally:
        try:
            path.unlink(missing_ok=True)
        except OSError:
            pass
