#!/usr/bin/env bash
set -euo pipefail

cd "$(dirname "${BASH_SOURCE[0]}")"

env_file="${1:-.env}"
if [[ -f "${env_file}" ]]; then
    echo "${env_file} already exists; leaving it unchanged."
    exit 0
fi

if ! command -v openssl >/dev/null 2>&1; then
    echo "openssl is required to generate n8n secrets." >&2
    exit 1
fi

host="${N8N_HOST:-}"
if [[ -z "${host}" ]]; then
    host="$(ip route get 1.1.1.1 2>/dev/null | sed -n 's/.*src \([^ ]*\).*/\1/p' | head -n1 || true)"
    host="${host:-localhost}"
fi

host_port="${N8N_HOST_PORT:-5678}"
protocol="${N8N_PROTOCOL:-http}"
timezone="${GENERIC_TIMEZONE:-Asia/Shanghai}"
postgres_password="${POSTGRES_PASSWORD:-$(openssl rand -hex 24)}"
encryption_key="${N8N_ENCRYPTION_KEY:-$(openssl rand -hex 32)}"

mkdir -p local-files
umask 077
cat >"${env_file}" <<EOF
# Generated by deploy/n8n/bootstrap-env.sh.
N8N_IMAGE=docker.n8n.io/n8nio/n8n
N8N_BIND_HOST=${N8N_BIND_HOST:-0.0.0.0}
N8N_HOST=${host}
N8N_HOST_PORT=${host_port}
N8N_PROTOCOL=${protocol}
WEBHOOK_URL=${protocol}://${host}:${host_port}/
N8N_EDITOR_BASE_URL=${protocol}://${host}:${host_port}/
N8N_SECURE_COOKIE=false

GENERIC_TIMEZONE=${timezone}

POSTGRES_DB=n8n
POSTGRES_USER=n8n
POSTGRES_PASSWORD=${postgres_password}
N8N_ENCRYPTION_KEY=${encryption_key}
EOF

echo "Wrote $(pwd)/${env_file}"
